package com.arsenii.CalculatorGUI.VisualCalculator.src;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.math.BigDecimal;


/**
 *
 * @author arsen
 */
public class CalculatorGUI extends javax.swing.JFrame {
    private double operandA;
    private double operandB;
    private String operator;
    boolean isRemainderAnswer = false;
    private BigDecimal Answer;    /**
     * Creates new form CalculatorGUI
     */
    public CalculatorGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        display = new javax.swing.JTextField();
        one = new javax.swing.JButton();
        two = new javax.swing.JButton();
        three = new javax.swing.JButton();
        four = new javax.swing.JButton();
        five = new javax.swing.JButton();
        six = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        add = new javax.swing.JButton();
        subtract = new javax.swing.JButton();
        multiply = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        equals = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        divWithRem = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("My wonderful calculator!");
        setMinimumSize(new java.awt.Dimension(250, 250));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        display.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        display.setText("                    ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        getContentPane().add(display, gridBagConstraints);

        one.setText("1");
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneButtonHandler(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        getContentPane().add(one, gridBagConstraints);

        two.setText("2");
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoButtonHandler(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        getContentPane().add(two, gridBagConstraints);

        three.setText("3");
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeButtonHandler(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        getContentPane().add(three, gridBagConstraints);

        four.setText("4");
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourButtonHandler(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        getContentPane().add(four, gridBagConstraints);

        five.setText("5");
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveButtonHandler(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        getContentPane().add(five, gridBagConstraints);

        six.setText("6");
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixButtonHandler(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        getContentPane().add(six, gridBagConstraints);

        seven.setText("7");
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenButtonHandler(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        getContentPane().add(seven, gridBagConstraints);

        eight.setText("8");
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightButtonHandler(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        getContentPane().add(eight, gridBagConstraints);

        nine.setText("9");
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineButtonHandler(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        getContentPane().add(nine, gridBagConstraints);

        add.setText("+");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonHandler(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        getContentPane().add(add, gridBagConstraints);

        subtract.setText("-");
        subtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtractButtonHandler(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        getContentPane().add(subtract, gridBagConstraints);

        multiply.setText("*");
        multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyButtonHandler(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        getContentPane().add(multiply, gridBagConstraints);

        divide.setText("/");
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideButtonHandler(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        getContentPane().add(divide, gridBagConstraints);

        Clear.setText("C");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonHandler(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        getContentPane().add(Clear, gridBagConstraints);

        zero.setText("0");
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroButtonHandler(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        getContentPane().add(zero, gridBagConstraints);

        equals.setText("=");
        equals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalsButtonHandler(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        getContentPane().add(equals, gridBagConstraints);

        Title.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Title.setText("Arsenii's Calculator");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        getContentPane().add(Title, gridBagConstraints);

        divWithRem.setText("%");
        divWithRem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divWithRemButtonHandler(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        getContentPane().add(divWithRem, gridBagConstraints);

        jButton1.setText(".");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotButtonHandler(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        getContentPane().add(jButton1, gridBagConstraints);

        jButton2.setText("<--");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackspaceButtonHandler(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        getContentPane().add(jButton2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void oneButtonHandler(java.awt.event.ActionEvent evt) {                                  
        // TODO add your handling code here:
        if (isRemainderAnswer == true) {
            display.setText("");
            isRemainderAnswer = false;
        }
        StringBuffer current = new StringBuffer(display.getText());
    	if (display.getText().equals("0")){
            display.setText("");
        }
        display.setText("" + current.append("1"));
    }

    private void twoButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoButtonHandler
        // TODO add your handling code here:
        if (isRemainderAnswer == true) {
            display.setText("");
            isRemainderAnswer = false;
        }
    	StringBuffer current = new StringBuffer(display.getText());
    	if (display.getText().equals("0")){
            display.setText("");
        }
        display.setText("" + current.append("2"));
    }//GEN-LAST:event_twoButtonHandler

    private void threeButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeButtonHandler
        // TODO add your handling code here:
        if (isRemainderAnswer == true) {
            display.setText("");
            isRemainderAnswer = false;
        }
    	StringBuffer current = new StringBuffer(display.getText());
    	if (display.getText().equals("0")){
            display.setText("");
        }
        display.setText("" + current.append("3"));
    }//GEN-LAST:event_threeButtonHandler

    private void fourButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourButtonHandler
        // TODO add your handling code here:
        if (isRemainderAnswer == true) {
            display.setText("");
            isRemainderAnswer = false;
        }
    	StringBuffer current = new StringBuffer(display.getText());
    	if (display.getText().equals("0")){
            display.setText("");
        }
        display.setText("" + current.append("4"));
    }//GEN-LAST:event_fourButtonHandler

    private void fiveButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveButtonHandler
        // TODO add your handling code here:
        if (isRemainderAnswer == true) {
            display.setText("");
            isRemainderAnswer = false;
        }
    	StringBuffer current = new StringBuffer(display.getText());
    	if (display.getText().equals("0")){
            display.setText("");
        }
        display.setText("" + current.append("5"));
    }//GEN-LAST:event_fiveButtonHandler

    private void sixButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixButtonHandler
        // TODO add your handling code here:
        if (isRemainderAnswer == true) {
            display.setText("");
            isRemainderAnswer = false;
        }
        StringBuffer current = new StringBuffer(display.getText());
    	if (display.getText().equals("0")){
            display.setText("");
        }
        display.setText("" + current.append("6"));
    }//GEN-LAST:event_sixButtonHandler

    private void sevenButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenButtonHandler
        // TODO add your handling code here:
        if (isRemainderAnswer == true) {
            display.setText("");
            isRemainderAnswer = false;
        }
    	StringBuffer current = new StringBuffer(display.getText());
    	if (display.getText().equals("0")){
            display.setText("");
        }
        display.setText("" + current.append("7"));
    }//GEN-LAST:event_sevenButtonHandler

    private void eightButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightButtonHandler
        // TODO add your handling code here:
        if (isRemainderAnswer == true) {
            display.setText("");
            isRemainderAnswer = false;
        }
    	StringBuffer current = new StringBuffer(display.getText());
    	if (display.getText().equals("0")){
            display.setText("");
        }
        display.setText("" + current.append("8"));
    }//GEN-LAST:event_eightButtonHandler

    private void nineButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineButtonHandler
        // TODO add your handling code here:
        if (isRemainderAnswer == true) {
            display.setText("");
            isRemainderAnswer = false;
        }
        StringBuffer current = new StringBuffer(display.getText());
    	if (display.getText().equals("0")){
            display.setText("");
        }
        display.setText("" + current.append("9"));
    }//GEN-LAST:event_nineButtonHandler

    private void ClearButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonHandler
        // TODO add your handling code here:
    	display.setText("");
    	isRemainderAnswer = false;
    }//GEN-LAST:event_ClearButtonHandler

    private void zeroButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroButtonHandler
        // TODO add your handling code here:
        if (isRemainderAnswer == true) {
            display.setText("");
            isRemainderAnswer = false;
        }
    	String current = display.getText();
    	if(current.equals("0")) {
    	    display.setText("0");
        }
    	else{
    	StringBuffer tmp = new StringBuffer(current);
    	display.setText("" + tmp.append("0"));
    	}
    }//GEN-LAST:event_zeroButtonHandler

    private void divWithRemButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divWithRemButtonHandler
        // TODO add your handling code here:
        operandA = Double.parseDouble(display.getText());
        operator = "%";
        display.setText("");
    }//GEN-LAST:event_divWithRemButtonHandler

    private void equalsButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalsButtonHandler
        // TODO add your handling code here:
        operandB = Double.parseDouble(display.getText());
        switch(operator){
            case "*": operandA *= operandB;
                Answer = new BigDecimal(Double.toString(operandA));
                display.setText("" + Answer.stripTrailingZeros().toPlainString());
                break;
            case "%": 
                if (!(operandB == 0.0)) {
            	    String answer = calculateWithRem(operandA, operandB);
            	    display.setText("" + answer);
                    operandA = 0.0;
                    operandB = 0.0;
                    isRemainderAnswer = true;
            	    break;
                }
                else {
                    display.setText("Error.");
                    operandA=0.0;operandB=0.0;
                    operator="";
                    break;
                }
            case "/" : 
                if (!(operandB == 0.0)) {
                    operandA /= operandB;
                    Answer = new BigDecimal(Double.toString(operandA));
                    display.setText("" + Answer.stripTrailingZeros().toPlainString());
                    break;
                }
                else {
                    display.setText("Error.");
                    operandA=0.0;operandB=0.0;
                    operator="";
                    break;
                }
            case "-": operandA -= operandB;
                Answer = new BigDecimal(Double.toString(operandA));
                display.setText("" + Answer.stripTrailingZeros().toPlainString());
                break;
            case "+": operandA += operandB;
                Answer = new BigDecimal(Double.toString(operandA));
                display.setText("" + Answer.stripTrailingZeros().toPlainString());
                break;
            default:

            }
    }//GEN-LAST:event_equalsButtonHandler

    private void addButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonHandler
        // TODO add your handling code here:
        operandA = Double.parseDouble(display.getText());
        operator = "+";
        display.setText("");
    }//GEN-LAST:event_addButtonHandler

    private void subtractButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtractButtonHandler
        // TODO add your handling code here:
        operandA = Double.parseDouble(display.getText());
        operator = "-";
        display.setText("");
    }//GEN-LAST:event_subtractButtonHandler

    private void multiplyButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyButtonHandler
        // TODO add your handling code here:
        operandA = Double.parseDouble(display.getText());
        operator = "*";
        display.setText("");
    }//GEN-LAST:event_multiplyButtonHandler

    private void divideButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideButtonHandler
        // TODO add your handling code here:
        operandA = Double.parseDouble(display.getText());
        operator = "/";
        display.setText("");
    }//GEN-LAST:event_divideButtonHandler

    private void BackspaceButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackspaceButtonHandler
        // TODO add your handling code here:
        String text = display.getText();
        String minus_one = text.substring(0,text.length() - 1);
        display.setText(minus_one);
    }//GEN-LAST:event_BackspaceButtonHandler

    private void dotButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotButtonHandler
        // TODO add your handling code here:
        StringBuffer current = new StringBuffer(display.getText());
         display.setText("" + current.append(".")); 
    }//GEN-LAST:event_dotButtonHandler

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorGUI().setVisible(true);
            }
        });
    }
    public String calculateWithRem(double first, double second) {
		long preAns = Math.round(first / second);
		long remainder = Math.round(first % second);
		BigDecimal remAnswer = new BigDecimal(preAns);
		String answer = (remAnswer.stripTrailingZeros().toPlainString() + ", R"+ remainder);
		return answer;
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JLabel Title;
    private javax.swing.JButton add;
    private javax.swing.JTextField display;
    private javax.swing.JButton divWithRem;
    private javax.swing.JButton divide;
    private javax.swing.JButton eight;
    private javax.swing.JButton equals;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton multiply;
    private javax.swing.JButton nine;
    private javax.swing.JButton one;
    private javax.swing.JButton seven;
    private javax.swing.JButton six;
    private javax.swing.JButton subtract;
    private javax.swing.JButton three;
    private javax.swing.JButton two;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
